default:
  image: "archlinux:latest"

stages:
  - lint
  - rootfs
  - image
  - test
  - release
  - publish

lint:
  stage: lint
  image: hadolint/hadolint:latest
  # DL3007: We use the latest tag for multistage build
  script: hadolint --ignore DL3007 --ignore DL3020 Dockerfile.template

.rootfs:
  stage: rootfs
  before_script:
    - echo "BUILD_VERSION=$(date +%Y%m%d).$CI_JOB_ID" > build.env
    - pacman -Syu --noconfirm make devtools fakechroot fakeroot
  artifacts:
    paths:
      - output/*
    expire_in: 2h
    reports:
      dotenv: build.env

rootfs:base:
  extends: .rootfs
  except:
    - master
    - add-base-devel-tags
    - schedules
    - tags
  script:
    - make $PWD/output/base.tar.xz $PWD/output/Dockerfile.base

rootfs:base-devel:
  extends: .rootfs
  except:
    - master
    - add-base-devel-tags
    - schedules
    - tags
  script:
    - make $PWD/output/base-devel.tar.xz $PWD/output/Dockerfile.base-devel

rootfs:base:secure:
  extends: .rootfs
  tags:
    - secure
  only:
    - master
    - add-base-devel-tags
    - schedules
    - tags
  script:
    - make $PWD/output/base.tar.xz $PWD/output/Dockerfile.base

rootfs:base-devel:secure:
  extends: .rootfs
  tags:
    - secure
  only:
    - master
    - add-base-devel-tags
    - schedules
    - tags
  script:
    - make $PWD/output/base-devel.tar.xz $PWD/output/Dockerfile.base-devel

.image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

image:base:
  extends: .image
  except:
    - master
    - add-base-devel-tags
    - schedules
    - tags
  script:
    - /kaniko/executor
      --whitelist-var-run="false"
      --context $CI_PROJECT_DIR/output
      --dockerfile $CI_PROJECT_DIR/output/Dockerfile.base
      --destination $CI_REGISTRY_IMAGE:base-$CI_COMMIT_REF_SLUG

image:base-devel:
  extends: .image
  except:
    - master
    - add-base-devel-tags
    - schedules
    - tags
  script:
    - /kaniko/executor
      --whitelist-var-run="false"
      --context $CI_PROJECT_DIR/output
      --dockerfile $CI_PROJECT_DIR/output/Dockerfile.base-devel
      --destination $CI_REGISTRY_IMAGE:base-devel-$CI_COMMIT_REF_SLUG

image:base:secure:
  extends: .image
  tags:
    - secure
  only:
    - master
    - add-base-devel-tags
    - schedules
    - tags
  script:
    - /kaniko/executor
      --whitelist-var-run="false"
      --context $CI_PROJECT_DIR/output
      --dockerfile $CI_PROJECT_DIR/output/Dockerfile.base
      --destination $CI_REGISTRY_IMAGE:base

image:base-devel:secure:
  extends: .image
  tags:
    - secure
  only:
    - master
    - add-base-devel-tags
    - schedules
    - tags
  script:
    - /kaniko/executor
      --whitelist-var-run="false"
      --context $CI_PROJECT_DIR/output
      --dockerfile $CI_PROJECT_DIR/output/Dockerfile.base-devel
      --destination $CI_REGISTRY_IMAGE:base-devel

.test:
  dependencies: []
  stage: test
  script:
    - pacman -Sy
    - pacman -Qqk
    - pacman -Syu --noconfirm docker grep
    - docker -v
    - id -u http
    - locale | grep -q UTF-8

test:base:
  extends: .test
  image: $CI_REGISTRY_IMAGE:base-$CI_COMMIT_REF_SLUG
  except:
    - master
    - add-base-devel-tags
    - schedules
    - tags

test:base-devel:
  extends: .test
  image: $CI_REGISTRY_IMAGE:base-devel-$CI_COMMIT_REF_SLUG
  except:
    - master
    - add-base-devel-tags
    - schedules
    - tags
  after_script:
    - gcc -v
    - g++ -v
    - make -v

test:base:secure:
  extends: .test
  tags:
    - secure
  only:
    - master
    - add-base-devel-tags
    - schedules
    - tags
  image: $CI_REGISTRY_IMAGE:base

test:base-devel:secure:
  extends: .test
  tags:
    - secure
  only:
    - master
    - add-base-devel-tags
    - schedules
    - tags
  image: $CI_REGISTRY_IMAGE:base-devel
  after_script:
    - gcc -v
    - g++ -v
    - make -v

release:
  stage: release
  tags:
    - secure
  only:
    refs:
      - schedules
    variables:
      - $SCHEDULED_PUBLISH == "TRUE"
  before_script:
    - pacman -Syu --noconfirm python-gitlab
  script:
    - python ci/release.py

# Publish base to the Arch Linux group namespace: https://hub.docker.com/r/archlinux/archlinux
publish:
  stage: publish
  tags:
    - secure
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  before_script:
    - echo $CI_REGISTRY_PASSWORD | crane auth login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - cat $DOCKER_ACCESS_TOKEN | crane auth login -u $DOCKER_USERNAME --password-stdin index.docker.io
  script:
    - crane cp $CI_REGISTRY_IMAGE:base archlinux/archlinux:base
    - crane tag archlinux/archlinux:base latest
    - crane tag archlinux/archlinux:base base-$BUILD_VERSION
    - crane cp $CI_REGISTRY_IMAGE:base-devel archlinux/archlinux:base-devel
    - crane tag archlinux/archlinux:base-devel base-devel-$BUILD_VERSION
  only:
    refs:
      - schedules
    variables:
      - $SCHEDULED_PUBLISH == "TRUE"

# Publish to the official Docker namespace: https://hub.docker.com/_/archlinux
# publish:official:
# TODO No idea right now how we're going to automatically do the official Docker Hub pull request
