stages:
  - lint
  - rootfs
  - image
  - test
  - release
  - publish

lint:
  stage: lint
  image: hadolint/hadolint:latest
  # DL3007: We use the latest tag for multistage build
  script: hadolint --ignore DL3007 --ignore DL3020 Dockerfile.template

.rootfs:
  stage: rootfs
  image: archlinux:latest
  before_script:
    - echo "BUILD_DATE=$(date +%Y%m%d)" > build.env
    - pacman -Syu --noconfirm make devtools fakechroot fakeroot
  artifacts:
    paths:
      - output/*
    expire_in: 2h
    reports:
      dotenv: build.env

rootfs:base:
  extends: .rootfs
  except:
    - master
    - schedules
    - tags
  script:
    - make output/base.tar.xz output/Dockerfile.base

rootfs:base-devel:
  extends: .rootfs
  except:
    - master
    - schedules
    - tags
  script:
    - make output/base-devel.tar.xz output/Dockerfile.base-devel

rootfs:base:secure:
  extends: .rootfs
  tags:
    - secure
  only:
    - master
    - schedules
    - tags
  script:
    - make output/base.tar.xz output/Dockerfile.base

rootfs:base-devel:secure:
  extends: .rootfs
  tags:
    - secure
  only:
    - master
    - schedules
    - tags
  script:
    - make output/base-devel.tar.xz output/Dockerfile.base-devel

.image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

image:base:
  extends: .image
  except:
    - master
    - schedules
    - tags
  script:
    - /kaniko/executor
      --whitelist-var-run="false"
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile.base
      --destination $CI_REGISTRY_IMAGE:base-$CI_COMMIT_REF_SLUG

image:base-devel:
  extends: .image
  except:
    - master
    - schedules
    - tags
  script:
    - /kaniko/executor
      --whitelist-var-run="false"
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile.base-devel
      --destination $CI_REGISTRY_IMAGE:base-devel-$CI_COMMIT_REF_SLUG

image:base:secure:
  extends: .image
  tags:
    - secure
  only:
    - master
    - schedules
    - tags
  script:
    - /kaniko/executor
      --whitelist-var-run="false"
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile.base
      --destination $CI_REGISTRY_IMAGE:base-$CI_COMMIT_REF_SLUG

image:base-devel:secure:
  extends: .image
  tags:
    - secure
  only:
    - master
    - schedules
    - tags
  script:
    - /kaniko/executor
      --whitelist-var-run="false"
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile.base-devel
      --destination $CI_REGISTRY_IMAGE:base-devel-$CI_COMMIT_REF_SLUG

# test:base:
#   stage: test
#   image: $CI_REGISTRY_IMAGE:base-$CI_COMMIT_REF_SLUG
#   dependencies: []
#   script:
#     - pacman -Sy
#     - pacman -Qqk
#     - pacman -Syu --noconfirm docker grep
#     - docker -v
#     - id -u http
#     - locale | grep -q UTF-8
#
# test:base-devel:
#   stage: test
#   image: $CI_REGISTRY_IMAGE:base-devel-$CI_COMMIT_REF_SLUG
#   dependencies: []
#   script:
#     - pacman -Sy
#     - pacman -Qqk
#     - pacman -Syu --noconfirm docker grep
#     - docker -v
#     - id -u http
#     - locale | grep -q UTF-8
#     - gcc -v
#     - g++ -v
#     - make -v
#
# release:
#   stage: release
#   image: archlinux:latest
#   only:
#     refs:
#       - master
#       - add-base-devel-tags
#     variables:
#       - $SCHEDULED_PUBLISH == "TRUE"
#   needs:
#     - job: "test:base"
#     - job: "test:base-devel"
#   before_script:
#     - pacman -Syu python-gitlab
#   script:
#     - python ci/release.py
#   tags:
#     - secure

# Publish base to the Arch Linux group namespace: https://hub.docker.com/r/archlinux/archlinux:base
# publish:org:base:
#   stage: publish
#   image:
#     name: gcr.io/go-containerregistry/crane:debug
#     entrypoint: [""]
#   needs:
#     - job: "test:base"
#       artifacts: true
#   tags:
#     - secure
#   variables:
#     GIT_STRATEGY: none
#   before_script:
#     - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - crane auth login -u $SOME_TECHNICAL_DOCKER_HUB_USER -p $SOME_TECHNICAL_DOCKER_HUB_PASSWORD archlinux/archlinux
#   script:
#     - crane cp $CI_REGISTRY_IMAGE:base-$CI_COMMIT_REF_SLUG archlinux/archlinux:base
#     - crane tag archlinux/archlinux:base latest
#     - crane tag archlinux/archlinux:base base-$BUILD_DATE
#   only:
#     variables:
#       - $SCHEDULED_PUBLISH == "TRUE"

# Publish base-devel to the Arch Linux group namespace: https://hub.docker.com/r/archlinux/archlinux:base-devel
# publish:org:base-devel:
#   stage: publish
#   image:
#     name: gcr.io/go-containerregistry/crane:debug
#     entrypoint: [""]
#   needs:
#     - job: "test:base-devel"
#       artifacts: true
#   tags:
#     - secure
#   variables:
#     GIT_STRATEGY: none
#   before_script:
#     - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - crane auth login -u $SOME_TECHNICAL_DOCKER_HUB_USER -p $SOME_TECHNICAL_DOCKER_HUB_PASSWORD archlinux/archlinux
#   script:
#     - crane cp $CI_REGISTRY_IMAGE:base-devel-$CI_COMMIT_REF_SLUG archlinux/archlinux:base-devel
#     - crane tag archlinux/archlinux:base-devel base-devel-$BUILD_DATE
#   only:
#     variables:
#       - $SCHEDULED_PUBLISH == "TRUE"

# Publish to the official Docker namespace: https://hub.docker.com/_/archlinux
# publish:official:
# TODO No idea right now how we're going to automatically do the official Docker Hub pull request
